Close #1128
reactiveui/refit pull request #1190
Opened 2021-06-17 08:53 UTC by jpbroeders

**What kind of change does this PR introduce?**
This PR solves a bug (#1128).

**What is the current behavior?**
 When getting back an HTTP 204 NoContent, the serializer will break because there is no body and content-type property, please see #1128

**What is the new behavior?**
New code is checking if the content-type is application/json. If not, it returns the default.

**What might this PR break?**
Nothing!

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

2021-06-17 09:26 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1190) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1190) before we can accept your contribution.<br/><br/>:x: jpbroeders [sign now](https://cla.dotnetfoundation.org/reactiveui/refit?pullRequest=1190)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/reactiveui/refit?pullRequest=1190) it.</sub>

2021-06-17 11:46 UTC, clairernovotny commented
Unfortunately this fix is more complicated than here. We can't return `null` or `default` for non-nullable return types. A 204 returns null, effectively. That means we have to detect if the return type is non-nullable or nullable so we can either return null or throw. 

Another workaround is to use `ApiResponse<>` or `HttpResponseMessage` return types where you can check the status before deserializing the object.

2021-06-17 11:58 UTC, jpbroeders commented
Thanks for the answer.
Because this is my first “contribution” in someones repo, I don’t know what to do with the pull request.
Should I close it?

From: Claire Novotny ***@***.***>
Sent: donderdag 17 juni 2021 13:47
To: reactiveui/refit ***@***.***>
Cc: Jean-Pierre Broeders ***@***.***>; State change ***@***.***>
Subject: Re: [reactiveui/refit] Fix Refit exception when getting 204 NoContent - Close #1128 (#1190)


Unfortunately this fix is more complicated than here. We can't return null or default for non-nullable return types. A 204 returns null, effectively. That means we have to detect if the return type is non-nullable or nullable so we can either return null or throw.

Another workaround is to use ApiResponse<> or HttpResponseMessage return types where you can check the status before deserializing the object.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://github.com/reactiveui/refit/pull/1190#issuecomment-863170861>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC42OFS4G7DP3GYCLOHLQGTTTHODDANCNFSM463GGHIQ>.

2021-06-17 11:59 UTC, clairernovotny requested changes
See my comment above. This issue is much more complicated.

2021-06-17 12:22 UTC, clairernovotny commented
This PR can be closed, thanks.

2021-06-17 12:58 UTC, closed without merging

2021-08-16 10:15 UTC, Thorarin commented
@clairernovotny That check cannot be performed at runtime, as far as I know.
At runtime, it's perfectly possible to assign null to a "non-nullable" reference type. 
Obviously, if your API can return empty content , you should use a nullable reference type in your Refit interface (if you're using #nullable enable), so the runtime behavior matches the type.

2022-08-09 04:45 UTC, AbdullahAlRana commented on Refit.Newtonsoft.Json/NewtonsoftJsonContentSerializer.cs
> +            if (responseMessage?.StatusCode == System.Net.HttpStatusCode.NoContent)
Interesting, I am wondering what if responseMessage is null